#!/usr/bin/env python3
"""
Create Pull Request for Agent Changes
Securely creates PR from agent modifications
"""

import os
import json
import subprocess
import datetime
from pathlib import Path

def create PullRequest():
    """Create a pull request with agent changes"""
    
    # Load changes from previous execution
    changes_file = Path(__file__).resolve().parents[1] / "changes.json"
    
    if not changes_file.exists():
        print("⚠️ No changes file found")
        return
    
    with open(changes_file, 'r') as f:
        changes = json.load(f)
    
    job_id = changes.get("job_id", "unknown")
    task = changes.get("task", "Unknown task")
    user_id = changes.get("user_id", "unknown")
    
    print(f"🔧 Creating PR for job {job_id}")
    
    # Create commit message
    commit_message = f"""feat: Autonomous agent completed task

Task: {task}
Job ID: {job_id}
User: {user_id}
Timestamp: {changes.get('timestamp', datetime.datetime.now().isoformat())}

Changes made:
{chr(10).join([f"- {change['action']}: {change['details']}" for change in changes.get('changes', [])])}

Files created:
{chr(10).join([f"- {file['path']} ({file['size']} bytes)" for file in changes.get('files', [])])}

Generated by Autonomous Agent
"""
    
    # Stage and commit changes
    try:
        # Configure git
        subprocess.run(['git', 'config', 'user.name', 'Autonomous Agent'], check=True)
        subprocess.run(['git', 'config', 'user.email', 'agent@autonomous.bot'], check=True)
        
        # Stage changes
        subprocess.run(['git', 'add', '-A'], check=True)
        
        # Check if there are changes to commit
        result = subprocess.run(['git', 'status', '--porcelain'], capture_output=True, text=True)
        if not result.stdout.strip():
            print("ℹ️ No changes to commit")
            return
        
        # Commit changes
        subprocess.run(['git', 'commit', '-m', commit_message], check=True)
        
        # Push current branch
        current_branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], 
                                      capture_output=True, text=True, check=True).stdout.strip()
        subprocess.run(['git', 'push', 'origin', current_branch], check=True)
        
        print(f"✅ Changes committed and pushed to {current_branch}")
        
    except subprocess.CalledProcessError as e:
        print(f"❌ Git operation failed: {e}")
        return
    
    # Create PR using GitHub CLI (works in Actions)
    try:
        pr_title = f"Autonomous Agent: {task[:50]}..."
        pr_body = f"""## Autonomous Agent Task Execution

**Task**: {task}
**Job ID**: {job_id}
**User**: {user_id}
**Completed**: {datetime.datetime.now().isoformat()}

### Summary
{task}

### Changes Made
{len(changes.get('files', []))} files created/modified

### Files Modified
{chr(10).join([f"- `{file['path']}`" for file in changes.get('files', [])])}

### Action Log
{chr(10).join([f"- {change['action']}: {change['details']}" for change in changes.get('changes', [])])}

---

⚠️ **Review required**: This PR contains autonomous AI agent changes. Please review before merging.

Generated by: Autonomous Agent
"""
        
        # Create PR
        result = subprocess.run([
            'gh', 'pr', 'create',
            '--title', pr_title,
            '--body', pr_body,
            '--label', 'autonomous-agent',
            '--assignee', 'self',
            '--head', os.environ.get('GITHUB_REF_NAME', current_branch),
            '--base', 'main'
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            print(f"🎉 Pull request created: {result.stdout.strip()}")
            
            # Save PR URL for notifications
            pr_url = result.stdout.strip()
            
            # Update changes with PR info
            changes['pr_url'] = pr_url
            changes['pr_title'] = pr_title
            changes['pr_created'] = datetime.datetime.now().isoformat()
            
            with open(changes_file, 'w') as f:
                json.dump(changes, f, indent=2)
            
            print(f"✅ PR URL saved: {pr_url}")
            
        else:
            print(f"❌ PR creation failed: {result.stderr}")
            
    except FileNotFoundError:
        print("⚠️ GitHub CLI not available, PR creation skipped")
    except subprocess.CalledProcessError as e:
        print(f"❌ PR creation failed: {e.stdout}")
    
    print("🔐 PR creation process completed")

if __name__ == "__main__":
    create PullRequest()