#!/usr/bin/env python3
"""
Send notifications to user about job completion
Uses Telegram bot for real-time updates
"""

import os
import json
import requests
import datetime
from pathlib import Path

def send_notification():
    """Send completion notification to user"""
    
    # Load changes from execution
    changes_file = Path(__file__).resolve().parents[1] / "changes.json"
    
    if not changes_file.exists():
        print("⚠️ No changes file found for notification")
        return
    
    with open(changes_file, 'r') as f:
        changes = json.load(f)
    
    job_id = changes.get("job_id", "unknown")
    task = changes.get("task", "Unknown task")
    user_id = changes.get("user_id", "unknown")
    pr_url = changes.get("pr_url", "")
    
    print(f"📱 Sending notification for job {job_id} to user {user_id}")
    
    # Prepare notification message
    message_lines = [
        "🎉 *Task Completed!*",
        "",
        f"📋 **Task**: {task}",
        f"🆔 **Job ID**: {job_id}",
        f"👤 **User**: {user_id}",
        f"⏰ **Completed**: {datetime.datetime.now().isoformat()}",
        "",
    ]
    
    if changes.get("files"):
        message_lines.extend([
            f"📁 **Files Modified**: {len(changes['files'])}",
            *[f" • `{file['path']}`" for file in changes['files'][:3]],
            f"• ... {len(changes['files']) - 3} more files" if len(changes['files']) > 3 else "",
            ""
        ])
    
    if pr_url:
        message_lines.extend([
            "🔀 **Pull Request**: [View Changes](" + pr_url + ")",
            ""
        ])
    
    message_lines.extend([
        "💬 *Review the changes and merge if satisfied!*",
        "",
        "_Generated by Autonomous Agent_"
    ])
    
    # Clean up empty lines
    message = "\n".join([line for line in message_lines if line.strip() or line.startswith(" ")]).strip()
    
    # Send via Telegram if token available
    telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
    if telegram_token and user_id != "unknown":
        try:
            url = f"https://api.telegram.org/bot{telegram_token}/sendMessage"
            payload = {
                'chat_id': user_id,
                'text': message,
                'parse_mode': 'Markdown'
            }
            
            response = requests.post(url, json=payload, timeout=10)
            
            if response.status_code == 200:
                print(f"✅ Notification sent to user {user_id}")
            else:
                print(f"❌ Notification failed: {response.text}")
                
        except Exception as e:
            print(f"❌ Telegram notification error: {e}")
    else:
        print("⚠️ Telegram token or user ID not available")
        print(f"📝 Message would be: {message[:200]}...")
    
    print("🔔 Notification process completed")

if __name__ == "__main__":
    send_notification()